// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define ModBusManager_ModBusNetwork_Observer_BODY

/************************************************************
 Observer class body
 ************************************************************/

// include associated header file
#include "Observer.h"

// Derived includes directives


namespace src {

// static attributes (if any)

/**
 * Destructor method
 * 
 * This is a virtual method, but, it also have a concrete implementaion, so, it is not a abstract method.
 * The concret implementation is necessary for delete objects created by derived subclasses.
 */
Observer::~Observer() {
}

} // of namespace src

/************************************************************
 End of Observer class body
 ************************************************************/
